name: DevSecOps Pipeline - Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Debug Files
      run: |
          ls -la
          cat sonar-project.properties  
    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@v2
      with:
        projectBaseDir: .
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

        
    - name: SonarCloud Quality Gate
      uses: SonarSource/sonarcloud-github-action@v2
      with:
        args: -Dsonar.qualitygate.wait=false  # for learning purose ..not acceptable at production
      env:
         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    - name: Trivy FS Scan
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        format: 'table'
        exit-code: '1'
        severity: 'CRITICAL'   #for learning purpose ..jobs should fail during high severity also

    - name: Build Docker Image
      run: docker build -t cloudnexus-app -f docker/Dockerfile . 

    - name: Trivy Image Scan
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'cloudnexus-app'
        format: 'table'
        exit-code: '1'
        severity: 'CRITICAL' #for learning purpose..jobs should fail during high severity also
  

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/key.pem
        chmod 600 ~/.ssh/key.pem

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'

          if [ ! -d "cloudnexus-devsecops" ]; then
            git clone https://github.com/Sudheerkadiyala2/cloudnexus-devsecops.git
          fi

          cd cloudnexus-devsecops

     
          git pull origin main

          sudo docker ps -q --filter "publish=5000" | xargs -r sudo docker stop
          sudo docker ps -aq --filter "publish=5000" | xargs -r sudo docker rm

          sudo docker run -d -p 5000:5000 --name cloudnexus-app cloudnexus-app

        EOF
