name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@v2
      with:
        args: >
          -Dsonar.projectKey=your_project_key
          -Dsonar.organization=your_org
          -Dsonar.sources=.
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    - name: SonarCloud Quality Gate
      uses: SonarSource/sonarcloud-quality-gate-action@v1
      timeout-minutes: 5
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    - name: Trivy FS Scan
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        format: 'table'
        exit-code: '1'
        severity: 'CRITICAL,HIGH'  

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/key.pem
        chmod 600 ~/.ssh/key.pem

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'

          if [ ! -d "cloudnexus-devsecops" ]; then
            git clone https://github.com/Sudheerkadiyala2/cloudnexus-devsecops.git
          fi

          cd cloudnexus-devsecops

     
          git pull origin main

          sudo docker ps -q --filter "publish=5000" | xargs -r sudo docker stop
          sudo docker ps -aq --filter "publish=5000" | xargs -r sudo docker rm

          sudo docker build -t cloudnexus-app -f docker/Dockerfile .

          sudo docker run -d -p 5000:5000 --name cloudnexus-app cloudnexus-app

        EOF
